"""Fill the description column in data/grammar.xlsx."""
from pathlib import Path
import openpyxl

XLSX_PATH = Path(__file__).parent.parent / "data" / "grammar.xlsx"

DESCRIPTIONS = {
    # L1
    0: "Positional nouns: 上下里外前后左右 and compass directions, plus their 边 forms",
    1: "Modal verbs 会 (know how to) and 能 (be able to)",
    2: "Modal verbs 想 (want to) and 要 (want / going to)",
    3: "Question pronouns: 多 多少 几 哪 哪儿 哪里 哪些 什么 谁 怎么",
    4: "Personal pronouns: 我 你 您 他 她 我们 你们 他们 她们",
    5: "Demonstrative pronouns: 这 那 这儿 那儿 这里 那里 这些 那些 别的 有的",
    6: "Numbers 1–9, 零, 十, 百, and 半",
    7: "Nominal measure words: 杯 本 个 家 间 口 块 页",
    8: "Degree adverbs: 非常 很 太 真 最",
    9: "Scope/joint adverbs: 都 一块儿 一起",
    10: "Time adverbs: 马上 先 有时 在 正 正在",
    11: "Frequency/repetition adverbs: 常 常常 再",
    12: "Linking adverbs: 还 也",
    13: "Negation adverbs: 另 不 没 没有",
    14: "Preposition 从 (from)",
    15: "Preposition 在 (at / in)",
    16: "Prepositions 跟 and 和 (with)",
    17: "Preposition 比 (compared to)",
    18: "Conjunctions 跟 还是 和 (and / or / with)",
    19: "Structural particles 的 and 地",
    20: "Aspect particle 了 (change of state or new situation)",
    21: "Modal particles 吧 了 吗 呢",
    22: "Numeral-measure phrases",
    23: "Nouns, pronouns, or nominal phrases as subject",
    24: "Verbs/verbal phrases and adjectives/adjectival phrases as predicate",
    25: "Nouns, pronouns, or nominal phrases as object",
    26: "Nominal, adjectival, and numeral-measure phrases as attribute (modifier before noun)",
    27: "Adverbs and adjectives as adverbial; time/place words as adverbial",
    28: "Subject-predicate sentences with verbal predicate",
    29: "Subject-predicate sentences with adjectival predicate",
    30: "Non-subject-predicate sentences (no explicit subject)",
    31: "Declarative sentences",
    32: "Interrogative sentences (overview)",
    33: "Imperative sentences",
    34: "Exclamatory sentences",
    35: "是-sentences (A is B)",
    36: "有-sentences type 1: expressing possession",
    37: "Comparative sentences type 1 (basic 比 comparison)",
    38: "Coordinate compound sentences (parallel clauses)",
    39: "Change-of-state aspect with 了",
    40: "Completion aspect with 了",
    41: "Progressive aspect (ongoing action, with 在/正/正在)",
    42: "Expressing money amounts",
    43: "Expressing time (clock time, dates)",
    44: "Asking questions with 吗",
    45: "Asking questions with 多/多少/几/哪/什么/谁/怎么 etc.",
    46: "Asking questions with 还是 (choice questions)",
    47: "Asking questions with A-not-A form",
    # L2
    48: "Modal verbs (review and additional uses)",
    49: "Modal verbs 该 and 应该 (should / ought to)",
    50: "Modal verb 愿意 (willing to)",
    51: "Verb reduplication: AA, A一A, A了A, ABAB (casual or brief action)",
    52: "Question pronouns: 多久 为什么 怎么样 怎样",
    53: "Personal pronouns: 别人 大家 它 它们 咱 咱们 自己",
    54: "Demonstrative pronouns: 那么 那样 这么 这样 (like this / like that)",
    55: "Adjective reduplication: AA and AABB (vivid description)",
    56: "Large numbers: 千 万 亿",
    57: "Ordinal number expressions",
    58: "Nominal measure words: 层 封 件 条 位",
    59: "Verbal measure words: 遍 次 场 回 下",
    60: "Duration measure words: 分钟 年 天 周",
    61: "Degree adverbs: 多 多么 好 更 十分 特别 挺 有（一）点儿",
    62: "Scope adverbs: 全 一共 只",
    63: "Time adverbs: 刚 刚刚 还 忽然 一直 已经",
    64: "Frequency/repetition adverbs: 重新 经常 老 老是 又",
    65: "Linking adverb 就 (then / right away)",
    66: "Manner adverb 故意 (on purpose / deliberately)",
    67: "Modal adverbs: 必须 差不多 好像 一定 也许",
    68: "Tone adverbs: 才 都 就 正好",
    69: "Preposition 当 (when / at the time of)",
    70: "Preposition 往 (toward a direction)",
    71: "Preposition 向 (toward / to)",
    72: "Preposition 从 (from) — extended uses",
    73: "Preposition 对 (toward / regarding)",
    74: "Preposition 给 (to / for)",
    75: "Preposition 离 (distance from)",
    76: "Preposition 为 (for the sake of)",
    77: "Conjunctions 或 and 或者 (or)",
    78: "Clause conjunctions: 不过 但 但是 而且 那 如果 虽然 只要",
    79: "Structural particle 得 (manner/degree complement marker)",
    80: "Aspect particle 过 (experiential: have done X before)",
    81: "Aspect particle 着 (ongoing state or manner)",
    82: "Modal particles 啊 吧 的",
    83: "Other particles: 的话 (if) and 等 (etc.)",
    84: "Interjection 喂 (hello / hey)",
    85: "Basic Chinese sentence structure types (overview)",
    86: "Other structure types 1 (additional sentence patterns)",
    87: "Nominal phrases",
    88: "Verbal phrases",
    89: "Adjectival phrases",
    90: "不一会儿 (in no time / very soon)",
    91: "什么的 (and so on / and the like)",
    92: "越来越 (more and more)",
    93: "还是⋯⋯吧 (it's better to... / had better)",
    94: "又⋯⋯又⋯⋯ (both... and...)",
    95: "（在）⋯⋯以前/以后 (before / after)",
    96: "Nouns, pronouns, numbers, or numeral-measure phrases as predicate",
    97: "Resultative complements type 1: verb + 错/懂/干净/好/会/清楚/完",
    98: "Directional complements type 1 (simple 来/去)",
    99: "State complement type 1: verb + 得 + adjective",
    100: "Quantity complement type 1: verb + verbal measure word",
    101: "Quantity complement type 2: adjective + measure word",
    102: "Subject-predicate sentences with nominal predicate",
    103: "有-sentences type 2: expressing existence at a location",
    104: "Cross-reference: Comparative sentences 2, subtypes (2)–(4)",
    105: "Existential sentences type 1: expressing existence",
    106: "Cross-reference: 有-sentences type 1, subtype (2)",
    107: "Serial verb sentences type 1: sequential actions",
    108: "Comparative sentences type 2 (using 没有 or 不如)",
    109: "Comparative sentences type 3 (using 有)",
    110: "是⋯⋯的 sentences type 1: emphasizing time, place, manner, or agent of a past action",
    111: "Double-object sentences (indirect + direct object)",
    112: "Sequential compound sentences (承接: one action follows another)",
    113: "Progressive/additive compound sentences (递进: not only... but also...)",
    114: "Alternative compound sentences (选择: either... or...)",
    115: "Adversative compound sentences (转折: although... but...)",
    116: "Hypothetical compound sentences (假设: if... then...)",
    117: "Conditional compound sentences: 只要⋯⋯就⋯⋯ (as long as... then...)",
    118: "Causal compound sentences (因果: because... therefore...)",
    119: "Contracted sentences: 一⋯⋯就⋯⋯ (as soon as... then...)",
    120: "Continuous aspect: verb + 着 (sustained state)",
    121: "Experiential aspect with 过 (has ever done X)",
    122: "Ordinal number expressions (第一, 第二, etc.)",
    123: "Approximate numbers type 1 (多, 来, 左右, 上下, etc.)",
    124: "Using 就 for emphasis (only / as few as / as early as)",
    125: "Cross-reference: 是⋯⋯的 sentences types 1 and 2",
    126: "Asking questions with 好吗/可以吗/行吗/怎么样",
    127: "Asking questions with 什么时候/什么样/为什么/怎么样/怎样",
    128: "Elliptical questions with 呢 (pronoun/noun + 呢?)",
    129: "Asking questions with 是不是",
    130: "Asking questions with 吧 (seeking confirmation)",
    131: "该⋯⋯了 (it's time to...)",
    132: "要/快要/就要⋯⋯了 (about to... / going to... soon)",
    # L3
    133: "Prefixes 第- (ordinal), 老- (familiar address), 小- (diminutive/address)",
    134: "Suffixes: 儿 (diminutive), 们 (plural), 头/子 (nominalizing)",
    135: "Modal verb 敢 (dare to / have the nerve to)",
    136: "Modal verb 需要 (need to / require)",
    137: "Verb-object separable words: 帮忙 点头 放假 干杯 见面 结婚 etc.",
    138: "Verb-complement separable words: 打开 看见 离开 完成 etc.",
    139: "Non-interrogative uses of question pronouns (referring to indefinite or universal referents)",
    140: "Demonstrative pronouns: 各 各位 各种 每 任何",
    141: "Nominal measure words: 把 行 架 群 束 双 台 张 支 只 种",
    142: "Verbal measure words: 顿 口 眼",
    143: "Measure word reduplication AA (one by one / each)",
    144: "Degree adverbs: 比较 更加 还 相当",
    145: "Scope adverbs: 光 仅 仅仅 就 至少",
    146: "Time adverbs: 本来 才 曾经 从来 赶紧 赶快 立刻 连忙 始终 已 早已",
    147: "Frequency adverbs: 通常 往往 总 总是",
    148: "Linking adverb 再 (then... / do Y after X)",
    149: "Manner adverbs: 互相 尽量 亲自 相互",
    150: "Modal adverbs: 大概 恐怕 (probably / I'm afraid)",
    151: "Tone adverbs: 白 并 当然 到底 反正 根本 果然 简直 绝对 难道 其实 千万 确实 只好 终于",
    152: "Preposition 由 (by / from / due to)",
    153: "Preposition 自从 (since a point in time)",
    154: "Preposition 朝 (toward / facing)",
    155: "Preposition 为 — extended uses",
    156: "Preposition 向 — extended uses",
    157: "Prepositions 由于 and 因为 (because of / due to)",
    158: "Preposition 为了 (in order to / for the purpose of)",
    159: "Prepositions 把 被 叫 让 (disposal and passive markers)",
    160: "Preposition 除了 (except for / besides)",
    161: "Prepositions 按 and 按照 (according to / in accordance with)",
    162: "Clause conjunctions: 并且 不光 不仅 另外 要是 因此 由于 只有",
    163: "Interjection 哈哈 (laughing)",
    164: "Other structure types 2",
    165: "Numeral-measure word reduplication (一个一个, 一天一天, etc.)",
    166: "不A不B (neither A nor B / not quite A, not quite B)",
    167: "看起来 (it looks like / it seems)",
    168: "看上去 (it appears / it looks)",
    169: "有的是 (there's plenty of / no shortage of)",
    170: "除了⋯⋯（以外），⋯⋯还/也/都⋯⋯ (besides... also / in addition to... also)",
    171: "从⋯⋯起 (starting from / beginning from)",
    172: "对⋯⋯来说 (for / as far as... is concerned)",
    173: "一……也/都+不/没 (not even one / not at all)",
    174: "越⋯⋯越⋯⋯ (the more... the more...)",
    175: "Verbs/verbal phrases and adjectives as subject",
    176: "Verbs, adjectives, and subject-predicate phrases as object",
    177: "Verbs, verbal phrases, and subject-predicate phrases as attribute",
    178: "Resultative complements type 2: verb + 到/住/走",
    179: "Directional complements type 2 (with full 来/去 compounds)",
    180: "Potential complements type 1: verb + 得/不 + result; verb + 得/不了",
    181: "Degree complements type 1: adjective/psychological verb + 得很/极了/死了",
    182: "Quantity complements type 3: co-occurrence of object and action measure",
    183: "Quantity complements type 4: duration expressing how long an action lasts",
    184: "Quantity complements type 5: duration expressing elapsed time since completion",
    185: "Subject-predicate sentences with a subject-predicate phrase as predicate",
    186: "把-sentences type 1: disposal (verb acts on the object of 把)",
    187: "Passive sentences type 1: subject + 被/叫/让 + agent + verb + other elements",
    188: "Serial verb sentences type 2 (two actions in sequence, second modifies first)",
    189: "Pivotal sentences type 1: object of first verb = subject of second verb",
    190: "Comparative sentences type 4 (using 没有...那么/这么)",
    191: "Resumed-verb sentences: subject + verb + object + verb + complement",
    192: "(也)⋯⋯，也⋯⋯ (also... also / either way...)",
    193: "一会儿⋯⋯，一会儿⋯⋯ (one moment... then... / alternating)",
    194: "一方面⋯⋯，另一方面⋯⋯ (on one hand... on the other...)",
    195: "又⋯⋯，又⋯⋯ (both... and... — simultaneous states)",
    196: "首先⋯⋯，然后⋯⋯ (first... then...)",
    197: "⋯⋯，并且⋯⋯ (... and furthermore...)",
    198: "不仅/不光⋯⋯，还/而且⋯⋯ (not only... but also...)",
    199: "不是⋯⋯，就是⋯⋯ (it's either... or...)",
    200: "X是X，就是/不过⋯⋯ (X is X, but... / conceding then qualifying)",
    201: "要是⋯⋯，就⋯⋯ (if... then...)",
    202: "只有⋯⋯，才⋯⋯ (only if... then...)",
    203: "（由于）⋯⋯，所以/因此⋯⋯ (because... therefore...)",
    204: "为了⋯⋯，⋯⋯ (in order to..., [action]...)",
    205: "⋯⋯了⋯⋯（就）⋯⋯ (once X is done, then...)",
    206: "Approximate numbers type 2 (几, 十几, 百把, etc.)",
    207: "Emphasis with 一点儿也不⋯⋯ (not even a little bit)",
    208: "Rhetorical questions for emphasis (反问句: 不是⋯⋯吗？ / 难道⋯⋯吗？)",
    209: "Using 是 for emphasis (emphasis on the predicate)",
    210: "Using rising intonation to form questions (no question particle)",
    211: "都⋯⋯了 (already / by now — expressing that something has reached a point)",
    212: "X就X（点儿）吧 (just go ahead and X / so what if X)",
    213: "X什么（啊） (what's the point of X? / dismissing or scolding)",
    # L4
    214: "Modal verb 得 (have to / must)",
    215: "Pronoun 人家 (other people / someone else / I — colloquial)",
    216: "Nominal measure words: 打 袋 根 卷 棵 批",
    217: "Borrowed measure words (nouns repurposed as measures, e.g. 桌 饭, 脸 泪)",
    218: "Degree adverbs: 格外 极 极其 (especially / extremely)",
    219: "Scope adverb 共 (altogether / in total)",
    220: "Time adverbs: 按时 即将 急忙 渐渐 尽快",
    221: "Frequency adverbs: 一再 再三 (repeatedly / time and again)",
    222: "Linking adverb 却 (yet / however — mild contrast)",
    223: "Negation adverb 未必 (not necessarily)",
    224: "Modal adverbs: 几乎 似乎 (almost / seemingly)",
    225: "Tone adverbs: 的确 反而 竟然 究竟",
    226: "Preposition 自 (from / since — formal)",
    227: "Preposition 对于 (regarding / with respect to)",
    228: "Preposition 关于 (about / concerning)",
    229: "Preposition 替 (on behalf of / in place of)",
    230: "Preposition 根据 (according to / based on)",
    231: "Preposition 作为 (as / in the capacity of)",
    232: "Conjunctions 并 and 以及 (and / as well as — formal)",
    233: "Clause conjunctions: 此外 而 而是 既然 可见 甚至 假如 总之",
    234: "Particle 似的 (like / as if — comparison)",
    235: "Interjection 啊 (ah / oh — various tones)",
    236: "大A大B pattern (big A big B — doing things in a big way)",
    237: "一A一B pattern (one A one B — paired, alternating, or careful)",
    238: "看来 (it seems / it appears — drawing a conclusion)",
    239: "来得及 / 来不及 (have / not have time to)",
    240: "说不定 (maybe / perhaps / hard to say)",
    241: "一般来说 (generally speaking)",
    242: "（自）⋯⋯以来 (since... / ever since...)",
    243: "由⋯⋯组成 (composed of / made up of)",
    244: "在⋯⋯方面 (in the area/aspect of)",
    245: "在⋯⋯上/下/中 (in/under/amid a context)",
    246: "Subject-predicate phrases as subject",
    247: "Affected object as subject (受事主语 — topic-prominent structure)",
    248: "Multiple attributes (ordering of stacked modifiers before a noun)",
    249: "Directional complements type 3 (with object placement)",
    250: "把-sentences type 2: extended disposal uses",
    251: "Passive sentences type 2: subject + 被 + verb + other elements",
    252: "Existential sentences type 2 (expressing appearance or disappearance)",
    253: "Pivotal sentences type 2",
    254: "是⋯⋯的 sentences type 2: emphasizing the speaker's view or stance",
    255: "不是⋯⋯，而是⋯⋯ (not... but rather...)",
    256: "既⋯⋯，又/也⋯⋯ (both... and... — formal)",
    257: "首先⋯⋯，其次⋯⋯ (firstly... secondly/furthermore...)",
    258: "⋯⋯，于是⋯⋯ (..., and so / thereupon...)",
    259: "⋯⋯，甚至⋯⋯ (..., and even...)",
    260: "或者⋯⋯，或者⋯⋯ (either... or...)",
    261: "⋯⋯，然而⋯⋯ (..., however...)",
    262: "⋯⋯，否则⋯⋯ (..., otherwise...)",
    263: "假如⋯⋯，（就）⋯⋯ (supposing..., then...)",
    264: "万一⋯⋯，（就）⋯⋯ (in case / just in case..., then...)",
    265: "不管⋯⋯，都/也⋯⋯ (no matter..., still...)",
    266: "无论⋯⋯，都/也⋯⋯ (regardless of..., still...)",
    267: "既然⋯⋯，就⋯⋯ (since / given that..., then...)",
    268: "⋯⋯，可见⋯⋯ (..., which shows / hence...)",
    269: "哪怕⋯⋯，也/还⋯⋯ (even if..., still...)",
    270: "⋯⋯，好⋯⋯ (..., so that / in order to...)",
    271: "Unmarked passive / implicit topic sentences (无标记)",
    272: "不⋯⋯也⋯⋯ (even without... still...)",
    273: "Approximate numbers type 3: numeral + 来 + measure (some twenty-odd...)",
    274: "Decimals, fractions, percentages, and multiples",
    275: "Rhetorical questions for emphasis",
    276: "Double negation for emphasis (不是不... / 没有不...)",
    277: "一+量词+也（都）不/没 for emphasis (not even one)",
    278: "连⋯⋯也/都⋯⋯ for emphasis (even... also / even... at all)",
    279: "不X白不X (you'd be a fool not to X / might as well X)",
    280: "动词+一X是一X (each instance of X counts / every bit of X matters)",
    281: "（没）有什么（好）X的 (nothing particularly worth X-ing / there's no need to X)",
    282: "X是X，Y是Y (X and Y are separate matters / keep them distinct)",
    283: "X也得X，不X也得X (X whether you like it or not / have to X regardless)",
    284: "X就是了 (just do X / all you need to do is X)",
    285: "还X呢 (you call that X? / dismissing something as inadequate)",
    286: "你X你的吧 (you go ahead and X / do your own thing)",
    287: "让/叫你X你就X (if told to X, just do it / do exactly as you're told)",
    288: "说什么/怎么（着）也得X (have to X no matter what)",
    # L5
    289: "Demonstrative pronouns: 彼此 (each other) and 如此 (like this / thus)",
    290: "Nominal measure words: 册 朵 幅 届 颗 匹 扇",
    291: "Degree adverbs: 过于 可 稍 稍微 尤其",
    292: "Scope adverb 大都 (mostly / for the most part)",
    293: "Time adverbs: 不时 将 将要 仍旧 时常 时刻 依旧 一向",
    294: "Frequency adverbs: 偶尔 (occasionally) and 再次 (once again)",
    295: "Manner adverb 偷偷 (stealthily / on the sly)",
    296: "Tone adverbs: 毕竟 不免 差（一）点儿 倒是 干脆 就 居然 可 明明 总算",
    297: "Preposition 随着 (along with / as ... progresses)",
    298: "Preposition 将 (about to — formal/written)",
    299: "Preposition 由 — extended uses",
    300: "Preposition 凭 (by means of / on the basis of)",
    301: "Preposition 依据 (based on / in accordance with)",
    302: "Preposition 依照 (in accordance with — formal)",
    303: "Clause connectors: 从而 加上 完了 一旦",
    304: "Particle 也好 (whether... or not / either way)",
    305: "A来A去 (doing X back and forth / repeatedly without result)",
    306: "A着A着 (while doing X, something gradually happens)",
    307: "没A没B (neither A nor B / lacking both)",
    308: "说A就A (do X without hesitation / at the drop of a hat)",
    309: "有A有B (has both A and B / well-rounded)",
    310: "不得了 (terrible / extreme / unbearable)",
    311: "不敢当 (I don't deserve it / you flatter me — polite refusal)",
    312: "得了 (that's enough / forget it — dismissal)",
    313: "用不着 (no need to / there's no point in)",
    314: "从⋯⋯来看 (looking at / judging from)",
    315: "到⋯⋯为止 (up to / until)",
    316: "够⋯⋯的 (quite... / pretty... — informal degree expression)",
    317: "拿⋯⋯来说 (taking... as an example)",
    318: "A的A，B的B (each doing their own thing / doing X and Y separately)",
    319: "在⋯⋯看来 (in [someone]'s view / from [someone]'s perspective)",
    320: "Semantic types of objects type 1 (patient, result, recipient, etc.)",
    321: "Multiple adverbials (ordering of stacked adverbials before verb)",
    322: "Directional complements type 4: extended time meaning (figurative use)",
    323: "Potential complements type 2: verb + 得/不得 (permissible / impermissible)",
    324: "Degree complements type 2 (beyond bare adjective forms)",
    325: "State complements type 2: verb/adjective + 得 + full phrase",
    326: "有-sentences type 3: expressing estimation or approximation",
    327: "把-sentences type 3: extended disposal uses",
    328: "Passive sentences type 3: notional passive (no overt passive marker)",
    329: "Serial verb sentences type 3: causal, concessive, or conditional relation between verbs",
    330: "Pivotal sentences type 3",
    331: "Comparative sentences type 5",
    332: "或是⋯⋯，或是⋯⋯ (either... or... — formal variant)",
    333: "尽管⋯⋯，但是/可是⋯⋯ (although..., nevertheless...)",
    334: "一旦⋯⋯，就⋯⋯ (once / if ever..., then...)",
    335: "要是⋯⋯，（就）⋯⋯，否则⋯⋯ (if..., then..., otherwise...)",
    336: "除非⋯⋯，才⋯⋯ (only if..., then... — exclusive condition)",
    337: "除非⋯⋯，否则/不然⋯⋯ (unless..., otherwise...)",
    338: "⋯⋯，因而⋯⋯ (..., and as a result...)",
    339: "即使⋯⋯，也⋯⋯ (even if..., still...)",
    340: "⋯⋯，为的是⋯⋯ (..., for the purpose of...)",
    341: "⋯⋯，以便⋯⋯ (..., so as to / in order to facilitate...)",
    342: "没有⋯⋯就没有⋯⋯ (without... there would be no...)",
    343: "再⋯⋯也⋯⋯ (no matter how..., still...)",
    344: "Complex compound sentences type 1 (single clause + compound, or compound + single)",
    345: "再也不/没⋯⋯ for emphasis (never again / no longer ever)",
    346: "Adverb 可 for emphasis (really / truly — colloquial intensifier)",
    347: "怎么都/也+不/没 for emphasis (no matter how, not...)",
    348: "X也不是，Y也不是 (neither X nor Y will do / stuck between two bad options)",
    349: "X也X不得，Y也Y不得 (can't do X, can't do Y either)",
    350: "X是它，Y也是它 (X is it and Y is it too — it serves both purposes)",
    351: "X着也是X着 (might as well X / X-ing without purpose)",
    352: "X归X，Y归Y (X is one matter, Y is another — keep them separate)",
    353: "不管怎样说 (no matter what / anyway / be that as it may)",
    354: "看你X的/瞧他X的 (look at how X you/he are — teasing or admiration)",
    355: "真有你/他/她的 (you/he/she are really something — impressed or exasperated)",
    356: "X什么X (what's so X about it? / dismissing)",
    357: "什么X不X（的） (who cares about X — dismissing a distinction)",
    358: "Using pronouns for cohesion (pronoun resumption / anaphora)",
    359: "Sentences with omitted elements (ellipsis in discourse)",
    # L6
    360: "Prefixes: 超- 多- 反- 无- 亚- 准-",
    361: "Suffixes: -化 -式 -型 -性",
    362: "Demonstrative pronouns: 本 and 此 (this / the present — formal)",
    363: "Nominal measure words: 餐 串 滴 副 股 集 枝",
    364: "Verbal measure words: 番 声 趟",
    365: "Degree adverbs: 特 异常 (especially / unusually — formal)",
    366: "Scope adverbs: 尽 净 一齐 一同",
    367: "Time adverbs: 时时 一时 早晚",
    368: "Linking adverb 便 (then / as soon as — formal written style)",
    369: "Manner adverbs: 不禁 赶忙 亲眼 特地 特意",
    370: "Modal adverb 仿佛 (as if / seemingly)",
    371: "Tone adverbs: 才 刚好 偏 恰好",
    372: "Preposition 于 (at/in/to/from — literary/formal)",
    373: "Preposition 沿（着） (along)",
    374: "Prepositions 同 and 与 (with / together with — formal)",
    375: "Preposition 至于 (as for / as to)",
    376: "Preposition 因 (because of / due to — formal)",
    377: "Preposition 除 (except / besides — formal)",
    378: "Preposition 据 (according to / based on — formal)",
    379: "Conjunctions 而 同 与 for connecting nouns/clauses (and / while — formal)",
    380: "Clause conjunctions: 不料 可 若",
    381: "Structural particle 所 (formal pre-verbal marker, as in 所说, 所做)",
    382: "Modal particles: 罢了 啦 嘛",
    383: "Numeral + adjective + measure word (e.g. 两大碗, 一小块)",
    384: "或A或B (either A or B — formal/literary)",
    385: "无A无B (neither A nor B — idiomatic)",
    386: "A这A那 (this A that A / doing X in various scattered ways)",
    387: "左A右B (left doing A right doing B / doing all sorts of things)",
    388: "不怎么 (not very / not particularly)",
    389: "不怎么样 (not very good / mediocre / nothing special)",
    390: "好（不）容易 (with great difficulty / finally managed to)",
    391: "那倒（也）是 (that's true / I'll grant you that)",
    392: "就是说/这就是说 (that is to say / in other words)",
    393: "算了 (forget it / let it go / never mind)",
    394: "A—+量词，B—+量词 (one A at a time, one B at a time — methodically)",
    395: "东一A，西一A (scattered here and there / haphazardly)",
    396: "为了⋯⋯而⋯⋯ (for the purpose of..., [do]... — formal)",
    397: "Semantic types of objects type 2",
    398: "Directional complements type 5 (abstract/extended meanings)",
    399: "把-sentences type 4: causative (causing an object to undergo a change)",
    400: "Passive sentences type 4: subject + 被/叫/让 + agent + 给 + verb",
    401: "时而⋯⋯，时而⋯⋯ (sometimes... sometimes... — alternating)",
    402: "一时⋯⋯一时⋯⋯ (at one moment... at another...)",
    403: "⋯⋯便⋯⋯ (..., then... — formal sequential)",
    404: "不但不/不但没有⋯⋯，反而⋯⋯ (not only not..., but on the contrary...)",
    405: "不是⋯⋯，还/还是⋯⋯ (isn't it..., still/or...)",
    406: "要么⋯⋯，要么⋯⋯ (either..., or... — must be one of the two)",
    407: "虽⋯⋯，但/可/却/也⋯⋯ (although..., still...)",
    408: "⋯⋯，要不然/不然⋯⋯ (..., otherwise...)",
    409: "凡是⋯⋯，都⋯⋯ (all those who... / whenever..., all...)",
    410: "就算/就是⋯⋯也⋯⋯ (even if..., still... — stronger concession)",
    411: "不⋯⋯不⋯⋯ (not without..., not unless...)",
    412: "Complex compound sentences type 2: compound clause + compound clause",
    413: "非⋯⋯不可 for emphasis (must / have no choice but to)",
    414: "X到Y头上来了 (X has gone so far as to affect Y / overstepping)",
    415: "X就X吧 (if it's X then X / so be it / accept the situation)",
    416: "X是X (granted that X / X is X — conceding a point)",
    417: "不X不⋯⋯，一X⋯⋯ (without X nothing happens, the moment you X...)",
    418: "好你个X (look at you being so X — mock scolding or admiration)",
    419: "动词+什么（就）是什么 (whatever is said goes / takes it as given)",
    420: "早（也）不X，晚（也）不X (not X early, not X late — bad timing)",
    421: "看/瞧把+[affected person]+X得 (look how X you've made [them])",
    422: "放着X不Y (having X available but choosing not to Y — wasteful)",
    423: "X来X去，都是/就是⋯⋯ (no matter how much X comes and goes, it's always...)",
    424: "X了就X了，（没）有⋯⋯ (what's done is done, (not) a big deal)",
    425: "这/那也不X，那/这也不Y (this way won't work, that way won't work either)",
    # L7-9
    426: "Modal verb 需 (need — formal/written register)",
    427: "Question pronoun 何 (what / how / where — classical Chinese)",
    428: "Demonstrative pronouns: 该 另 兹 (the said / another / hereby — formal)",
    429: "Nominal measure words used in formal or classical contexts",
    430: "极为 (extremely — formal written style)",
    431: "尽 (as fully as possible / to the utmost)",
    432: "蛮 (quite / rather — southern Chinese colloquial)",
    433: "颇 (rather / considerably — literary)",
    434: "稍稍 (slightly / a little — softer than 稍微)",
    435: "尤为 (especially / particularly — formal)",
    436: "越发 (increasingly / all the more — formal)",
    437: "凡 (every / all — formal/classical)",
    438: "皆 (all / everyone — literary/classical)",
    439: "统统 (all / the whole lot — colloquial emphasis)",
    440: "唯独 (only / solely — singling out one exception)",
    441: "即 (immediately / namely — formal; abbreviation for 就是)",
    442: "历来 (always / throughout history / from time immemorial)",
    443: "尚 (still / yet / also — formal/literary)",
    444: "向来 (always / has always been the case)",
    445: "频频 (repeatedly / frequently — formal written style)",
    446: "再度 (again / once more — formal)",
    447: "亦 (also / too — classical/literary equivalent of 也)",
    448: "未 (not yet / have not — classical negation)",
    449: "勿 (do not — classical imperative negation)",
    450: "不由得 (can't help but / involuntarily)",
    451: "顺便 (conveniently / while you're at it / in passing)",
    452: "一连 (one after another / in succession / in a row)",
    453: "按说 (ordinarily / by rights / logically one would expect)",
    454: "必定 (certainly / definitely — formal)",
    455: "不妨 (might as well / there's no harm in / feel free to)",
    456: "何必 (why bother / there's no need to)",
    457: "莫非 (can it be that / don't tell me — rhetorical surprise)",
    458: "白白 (in vain / for nothing / wasted)",
    459: "反倒 (on the contrary / instead — unexpected reversal)",
    460: "分明 (clearly / obviously / it's plain that)",
    461: "怪不得 (no wonder / that explains it)",
    462: "好在 (fortunately / luckily / the good thing is)",
    463: "乃 (is / be / then — classical copula and connector)",
    464: "难怪 (no wonder / it's no surprise / that's why)",
    465: "偏偏 (contrary to expectations / just happens to / of all things)",
    466: "索性 (simply / just go ahead and / may as well)",
    467: "万万 (absolutely not / by no means — strong negation intensifier)",
    468: "未免 (a bit too / rather — mild criticism of excess)",
    469: "无非 (nothing but / merely / it's just that)",
    470: "幸好 (fortunately / luckily)",
    471: "幸亏 (fortunately / thanks to — emphasizing the saving factor)",
    472: "终究 (in the end / ultimately / after all)",
    473: "顺着 (following along / going along with)",
    474: "当着 (in the presence of / in front of)",
    475: "就5 (preposition 就: right at / up against)",
    476: "趁 (while / taking advantage of the opportunity)",
    477: "基于 (based on / in light of — formal)",
    478: "依 (according to / in accordance with — formal)",
    479: "Conjunction 及 (and / as well as — formal written)",
    480: "Clause connectors: 继而 (then/thereafter) and 要不是 (if not for)",
    481: "Classical particle 之 (of / verbal object marker — classical/formal)",
    482: "而已 (that's all / merely — written sentence-final)",
    483: "Classical sentence-final particle 矣 (assertion/completion — classical)",
    484: "Numeral + measure word + abstract noun (e.g. 一股劲, 一番话)",
    485: "爱A不A (take it or leave it / do as you please — indifference)",
    486: "半A半B (half A half B / a mixture of two states)",
    487: "东A西B (doing things all over the place / scattered activities)",
    488: "非A非B (neither A nor B — formal/literary)",
    489: "忽A忽B (now A now B / fluctuating between two states)",
    490: "连A带B (A and B together / along with / including both)",
    491: "时A时B (sometimes A sometimes B — alternating)",
    492: "自A自B (doing A and B of one's own accord / self-sufficiently)",
    493: "巴不得 (can't wait to / earnestly wish one could)",
    494: "别提了 (don't even bring it up / you can imagine how bad it was)",
    495: "除此之外 (besides this / apart from this / in addition)",
    496: "归根到底 (in the final analysis / when all is said and done)",
    497: "可不是 (exactly! / isn't that right! — strong agreement)",
    498: "没说的 (goes without saying / no complaints / top-notch)",
    499: "无论如何 (no matter what / under any circumstances)",
    500: "由此可见 (from this we can see / hence / this shows that)",
    501: "与此同时 (at the same time / meanwhile)",
    502: "这样一来 (as a result of this / this being the case)",
    503: "综上所述 (in summary / to sum up the foregoing — formal written)",
    504: "总的来说/总而言之 (in general / in a word / to sum up)",
    505: "不知⋯⋯好 (don't know what... to do / at a total loss)",
    506: "所谓⋯⋯就是⋯⋯ (what is called... is... / defining the so-called)",
    507: "无非/不过/只不过/只是⋯⋯而已/罢了 (nothing more than... / merely... that's all)",
    508: "以⋯⋯为⋯⋯ (taking... as... / treating... as... — formal)",
    509: "因⋯⋯而⋯⋯ (because of..., [result]... — formal)",
    510: "Semantic types of objects type 3 (abstract, propositional, etc.)",
    511: "Degree complements type 3 (more complex or literary forms)",
    512: "State complements type 3: complement led by 个 (verb + 个 + complement)",
    513: "把-sentences type 5: causative (formal/literary contexts)",
    514: "Passive sentences type 5 (formal and classical passive constructions)",
    515: "Comparative sentences type 6 (formal or complex comparisons)",
    516: "一面⋯⋯，一面⋯⋯ (at the same time... / simultaneously doing two things)",
    517: "⋯⋯，此后⋯⋯ (..., after that / thereafter — formal narrative)",
    518: "起初⋯⋯，⋯⋯才⋯⋯ (at first..., only then...)",
    519: "别说⋯⋯，连⋯⋯也/都 and variants (let alone... even... / not even...)",
    520: "⋯⋯，何况⋯⋯ (..., let alone / much less... — a fortiori)",
    521: "⋯⋯，进而⋯⋯ (..., and then going further...)",
    522: "⋯⋯，况且⋯⋯ (..., moreover / besides — adding a stronger reason)",
    523: "连⋯⋯，更不用说⋯⋯ (even..., let alone...)",
    524: "⋯⋯，乃至⋯⋯ (..., and even / going as far as... — formal)",
    525: "⋯⋯，且⋯⋯ (..., and / moreover — literary conjunction)",
    526: "⋯⋯，甚至于⋯⋯ (..., going so far as to...)",
    527: "或⋯⋯，或⋯⋯ (either..., or... — literary/formal)",
    528: "宁可/宁愿⋯⋯ (would rather... — stating the preferred side)",
    529: "与其⋯⋯，不如⋯⋯ (rather than..., better to...)",
    530: "与其⋯⋯，宁可/宁愿⋯⋯ (rather than..., would prefer to...)",
    531: "⋯⋯，而⋯⋯（则）⋯⋯ (..., whereas... — formal contrast)",
    532: "⋯⋯，⋯⋯倒/反倒⋯⋯ (..., unexpectedly on the contrary...)",
    533: "倘若/若⋯⋯，⋯⋯ (if / supposing... — literary conditional)",
    534: "倘若/假设/假使/若⋯⋯，就/那（么）⋯⋯ (if/should..., then... — literary)",
    535: "幸亏⋯⋯，要不然/不然⋯⋯ (fortunately..., otherwise...)",
    536: "别管⋯⋯，都⋯⋯ (no matter what / regardless of..., still...)",
    537: "任⋯⋯，也⋯⋯ (no matter what / however..., still... — formal)",
    538: "（因）⋯⋯，故⋯⋯ (because..., therefore... — classical)",
    539: "鉴于⋯⋯，⋯⋯ (in view of / given..., ... — formal)",
    540: "（由于）⋯⋯，以致⋯⋯ (owing to..., resulting in... — negative consequence)",
    541: "⋯⋯，以至于⋯⋯ (..., to the point that / so much so that...)",
    542: "之所以⋯⋯，是因为/是由于⋯⋯ (the reason why... is because...)",
    543: "固然⋯⋯，也⋯⋯ (granted..., but also... — conceding while adding)",
    544: "⋯⋯固然⋯⋯，但是/可是/不过⋯⋯ (granted..., but...)",
    545: "即便⋯⋯，也⋯⋯ (even if..., still... — formal variant of 即使)",
    546: "虽说⋯⋯，但是/可是/不过⋯⋯ (though / although..., but... — spoken formal)",
    547: "纵然⋯⋯，也⋯⋯ (even though..., still... — literary concessive)",
    548: "⋯⋯，以⋯⋯ (..., so as to / in order to — formal purposive)",
    549: "⋯⋯，以免/免得⋯⋯ (..., so as to avoid / lest...)",
    550: "⋯⋯，也就是说⋯⋯ (..., in other words / that is to say...)",
    551: "（要+）动词+就+动词+个+补语 (if you're going to do X, do it all the way)",
    552: "动词（+宾语）+就+动词（+宾语），别⋯⋯ (just do the verb, don't [add more])",
    553: "Three-level or higher compound sentences",
    554: "Rhetorical questions: 何必/何苦⋯⋯呢？ (why bother? / why put yourself through X?)",
    555: "话又说回来⋯⋯ (but then again / that said / having said that)",
    556: "X（也）不是，不X也不是 (damned if you do, damned if you don't)",
    557: "X也好/也罢，Y也好/也罢 (whether X or Y, it doesn't matter)",
    558: "X了又Y，Y了又X (a cycle of X and Y / endlessly going back and forth)",
    559: "X也X不⋯⋯，Y也Y不⋯⋯ (can't quite X, can't quite Y either)",
    560: "别提（有）多X了 (indescribably X / you can't imagine how X)",
    561: "不知X的 (inexplicably X / oddly X — describing unexpected quality)",
    562: "话（说）是这么说，不过/可/可是⋯⋯ (that may be true, but...)",
    563: "看/瞧你那（X）样 (look at you / look at the state of you — teasing)",
    564: "看在X的面子上 (for the sake of X / out of respect for X)",
    565: "哪有X这么Y的/有X这样Y的吗 (how can X be so Y? / is there such a thing as X being Y?)",
    566: "什么X的Y的 (all sorts of X and Y / this and that)",
    567: "说到/想到哪儿去了 (you've gone off topic / that's not what I meant at all)",
    568: "无所谓X不X (it doesn't matter whether X or not / couldn't care less)",
    569: "要X有/没X，要Y有/没Y (has/hasn't X, has/hasn't Y — listing what's available or lacking)",
    570: "Complex sentences linked with correlative conjunctions (带关联词语)",
    571: "Complex sentences without correlative conjunctions (带关联词语)",
    572: "Coordinate sentence groups: parallel, sequential, progressive, alternative, explanatory, summarizing",
    573: "Subordinate sentence groups: conditional, causal, purposive, adversative, hypothetical, concessive",
}


def apply_descriptions():
    wb = openpyxl.load_workbook(XLSX_PATH)
    ws = wb.active
    rows = list(ws.iter_rows(min_row=2, values_only=True))
    updated = 0
    for row_idx, row in enumerate(rows):
        if row_idx not in DESCRIPTIONS:
            continue
        existing_desc = row[3]
        if existing_desc:
            continue  # don't overwrite
        desc = DESCRIPTIONS[row_idx]
        ws.cell(row=row_idx + 2, column=4, value=desc)
        updated += 1
    wb.save(XLSX_PATH)
    print(f"Updated {updated} rows in {XLSX_PATH}")


if __name__ == "__main__":
    apply_descriptions()
